# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comm.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='comm.proto',
  package='',
  serialized_pb='\n\ncomm.proto\"\x92\x02\n\rPhotoResponse\x12:\n\x0cresponseFlag\x18\x01 \x02(\x0e\x32\x1b.PhotoResponse.ResponseFlag:\x07success\x12\x37\n\x0cresponseType\x18\x02 \x02(\x0e\x32\x1b.PhotoResponse.ResponseType:\x04read\x12\x14\n\x0clastModified\x18\x03 \x01(\x03\x12\x0c\n\x04uuid\x18\x04 \x01(\t\x12\r\n\x05photo\x18\x05 \x01(\x0c\"(\n\x0cResponseFlag\x12\x0b\n\x07success\x10\x00\x12\x0b\n\x07\x66\x61ilure\x10\x01\"/\n\x0cResponseType\x12\x08\n\x04read\x10\x00\x12\t\n\x05write\x10\x01\x12\n\n\x06\x64\x65lete\x10\x02\"\x9e\x01\n\x0cPhotoRequest\x12\x34\n\x0brequestType\x18\x01 \x02(\x0e\x32\x19.PhotoRequest.RequestType:\x04read\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\".\n\x0bRequestType\x12\x08\n\x04read\x10\x00\x12\t\n\x05write\x10\x01\x12\n\n\x06\x64\x65lete\x10\x02\x42\x05\n\x03\x65ye')



_PHOTORESPONSE_RESPONSEFLAG = _descriptor.EnumDescriptor(
  name='ResponseFlag',
  full_name='PhotoResponse.ResponseFlag',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='success', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='failure', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=200,
  serialized_end=240,
)

_PHOTORESPONSE_RESPONSETYPE = _descriptor.EnumDescriptor(
  name='ResponseType',
  full_name='PhotoResponse.ResponseType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='read', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='write', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='delete', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=242,
  serialized_end=289,
)

_PHOTOREQUEST_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='PhotoRequest.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='read', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='write', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='delete', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=404,
  serialized_end=450,
)


_PHOTORESPONSE = _descriptor.Descriptor(
  name='PhotoResponse',
  full_name='PhotoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseFlag', full_name='PhotoResponse.responseFlag', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='responseType', full_name='PhotoResponse.responseType', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastModified', full_name='PhotoResponse.lastModified', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='PhotoResponse.uuid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='photo', full_name='PhotoResponse.photo', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PHOTORESPONSE_RESPONSEFLAG,
    _PHOTORESPONSE_RESPONSETYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=15,
  serialized_end=289,
)


_PHOTOREQUEST = _descriptor.Descriptor(
  name='PhotoRequest',
  full_name='PhotoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestType', full_name='PhotoRequest.requestType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='PhotoRequest.uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='PhotoRequest.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='PhotoRequest.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PHOTOREQUEST_REQUESTTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=292,
  serialized_end=450,
)

_PHOTORESPONSE.fields_by_name['responseFlag'].enum_type = _PHOTORESPONSE_RESPONSEFLAG
_PHOTORESPONSE.fields_by_name['responseType'].enum_type = _PHOTORESPONSE_RESPONSETYPE
_PHOTORESPONSE_RESPONSEFLAG.containing_type = _PHOTORESPONSE;
_PHOTORESPONSE_RESPONSETYPE.containing_type = _PHOTORESPONSE;
_PHOTOREQUEST.fields_by_name['requestType'].enum_type = _PHOTOREQUEST_REQUESTTYPE
_PHOTOREQUEST_REQUESTTYPE.containing_type = _PHOTOREQUEST;
DESCRIPTOR.message_types_by_name['PhotoResponse'] = _PHOTORESPONSE
DESCRIPTOR.message_types_by_name['PhotoRequest'] = _PHOTOREQUEST

class PhotoResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PHOTORESPONSE

  # @@protoc_insertion_point(class_scope:PhotoResponse)

class PhotoRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PHOTOREQUEST

  # @@protoc_insertion_point(class_scope:PhotoRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\003eye')
# @@protoc_insertion_point(module_scope)
